### PR TITLE
Update Kotlin to 1.8.22

### PR DESCRIPTION
**Pull request by russellbanks**
- Updates Kotlin to 1.8.22
- Updates Gradle to 8.1.1 to support this
- Replaces deprecated `kotlinOptions.jvmTarget` with type-safe `compilerOptions.jvmTarget`

### CODE REVIEW

**Comment by russellbanks** [comment]
@AChep, I've fixed the conflicts and updated to Kotlin 1.8.22. My project is having some issues with KotlinX DateTime since adding this project's dependency, which I think is down to the outdated Kotlin version.

**Comment by AChep** [comment]
@russellbanks any chance we update to the latest version of Kotlin supported by the stable version of Multiplatform Compose? I believe that's `1.8.20` but I'll check that later today.

**Comment by russellbanks** [comment]
> @russellbanks any chance we update to the latest version of Kotlin supported by the stable version of Multiplatform Compose? I believe that's `1.8.20` but I'll check that later today.

I can do that if you want but we only need to follow that versioning as a library if we rely on Multiplatform Compose as a dependency. As long as projects that use this library use that Kotlin version if they rely on it, then it will still work fine.

**Comment by AChep** [comment]
For some reason I can't merge because of the conflicts But it doesn't say what files exactly have conflicts. :thinking:

**Comment by russellbanks** [comment]
> For some reason I can't merge because of the conflicts But it doesn't say what files exactly have conflicts. 🤔

Hmm GitHub says "This branch has no conflicts with the base branch". If you're still not able to, there's GitHub CLI?

**Comment by AChep** [comment]
Took a bit different approach, the build with Kotlin 1.8.22 should be available soon :)

**Comment by russellbanks** [comment]
@AChep The gradle binary still needs updating. You can do that by running `./gradlew wrapper --gradle-version=8.2`

**Pull request closed without merging**
